use anyhow::{Context, Result};
use base64::{Engine as _, engine::general_purpose::STANDARD as BASE64};
use clap::Parser;
use regex::Regex;
use std::collections::HashMap;
use std::fs;
use std::io::{self, Read, Write as IoWrite};
use std::path::{Path, PathBuf};
use std::process::Command;
use tempfile::NamedTempFile;

// Include embedded icons (generated by build.rs)
include!(concat!(env!("OUT_DIR"), "/icons.rs"));

#[derive(Parser, Debug)]
#[command(name = "agedashi")]
#[command(about = "Generate infrastructure diagrams from Terraform/OpenTofu graph output - making tofu pretty!", long_about = None)]
struct Cli {
    /// Output format (svg, png, pdf, jpg)
    #[arg(short, long, default_value = "png")]
    output: String,

    /// Output file name (without extension)
    #[arg(short, long, default_value = "infrastructure")]
    name: String,

    /// Show graph direction (TB=top-to-bottom, LR=left-to-right)
    #[arg(short, long, default_value = "TB")]
    direction: String,

    /// Color for edges and text (hex color code)
    #[arg(short, long, default_value = "#2D3436")]
    color: String,
}

#[derive(Debug, Clone)]
struct TerraformResource {
    name: String,
    resource_type: String,
    label: String,
}

#[derive(Debug)]
struct TerraformGraph {
    resources: Vec<TerraformResource>,
    edges: Vec<(String, String)>,
}

impl TerraformGraph {
    fn new() -> Self {
        Self {
            resources: Vec::new(),
            edges: Vec::new(),
        }
    }

    fn add_resource(&mut self, name: String, resource_type: String, label: String) {
        self.resources.push(TerraformResource {
            name,
            resource_type,
            label,
        });
    }

    fn add_edge(&mut self, from: String, to: String) {
        self.edges.push((from, to));
    }
}

fn get_cache_dir() -> Result<PathBuf> {
    let cache_dir = if let Ok(home) = std::env::var("HOME") {
        PathBuf::from(home).join(".cache").join("agedashi").join("icons")
    } else if let Ok(userprofile) = std::env::var("USERPROFILE") {
        PathBuf::from(userprofile).join(".cache").join("agedashi").join("icons")
    } else {
        PathBuf::from("/tmp").join("agedashi").join("icons")
    };

    fs::create_dir_all(&cache_dir)
        .context("Failed to create cache directory")?;

    Ok(cache_dir)
}

fn extract_embedded_icons(cache_dir: &Path) -> Result<()> {
    let embedded_icons = get_embedded_icons();

    for (name, data) in embedded_icons {
        let icon_path = cache_dir.join(format!("{}.png", name));

        // Only write if file doesn't exist
        if !icon_path.exists() {
            fs::write(&icon_path, data)
                .context(format!("Failed to extract icon: {}", name))?;
        }
    }

    Ok(())
}

fn convert_svg_to_png(svg_path: &Path, png_path: &Path, size: u32) -> Result<()> {
    // Read the SVG file
    let svg_data = fs::read(svg_path)
        .context("Failed to read SVG file")?;

    // Parse the SVG with default options
    let tree = usvg::Tree::from_data(&svg_data, &usvg::Options::default())
        .map_err(|e| anyhow::anyhow!("Failed to parse SVG: {}", e))?;

    // Get the SVG size and calculate the scaling factor
    let svg_size = tree.size();
    let scale = if svg_size.width() > svg_size.height() {
        size as f32 / svg_size.width()
    } else {
        size as f32 / svg_size.height()
    };

    // Create a pixmap with the desired size
    let mut pixmap = tiny_skia::Pixmap::new(size, size)
        .ok_or_else(|| anyhow::anyhow!("Failed to create pixmap"))?;

    // Render the SVG to the pixmap with scaling
    let transform = tiny_skia::Transform::from_scale(scale, scale);
    resvg::render(&tree, transform, &mut pixmap.as_mut());

    // Apply rounded corners
    let corner_radius = (size as f32 * 0.1) as f32; // 10% radius for nice rounded corners
    apply_rounded_corners(&mut pixmap, corner_radius);

    // Save as PNG
    pixmap.save_png(png_path)
        .map_err(|e| anyhow::anyhow!("Failed to save PNG: {}", e))?;

    Ok(())
}

fn apply_rounded_corners(pixmap: &mut tiny_skia::Pixmap, radius: f32) {
    use tiny_skia::*;

    let width = pixmap.width() as f32;
    let height = pixmap.height() as f32;

    // Create a path with rounded rectangle
    let mut path_builder = PathBuilder::new();

    // Start at top-left corner (after rounding)
    path_builder.move_to(radius, 0.0);

    // Top edge
    path_builder.line_to(width - radius, 0.0);

    // Top-right corner
    path_builder.quad_to(width, 0.0, width, radius);

    // Right edge
    path_builder.line_to(width, height - radius);

    // Bottom-right corner
    path_builder.quad_to(width, height, width - radius, height);

    // Bottom edge
    path_builder.line_to(radius, height);

    // Bottom-left corner
    path_builder.quad_to(0.0, height, 0.0, height - radius);

    // Left edge
    path_builder.line_to(0.0, radius);

    // Top-left corner
    path_builder.quad_to(0.0, 0.0, radius, 0.0);

    path_builder.close();

    let path = path_builder.finish().unwrap();

    // Create a mask pixmap
    let mut mask = Pixmap::new(pixmap.width(), pixmap.height()).unwrap();

    // Fill the mask with the rounded rectangle
    let mut paint = Paint::default();
    paint.set_color_rgba8(255, 255, 255, 255);

    mask.fill_path(
        &path,
        &paint,
        FillRule::Winding,
        Transform::identity(),
        None,
    );

    // Apply the mask to the original pixmap
    let width = pixmap.width();
    let height = pixmap.height();

    for y in 0..height {
        for x in 0..width {
            let mask_pixel = mask.pixel(x, y).unwrap();

            // If the mask is transparent at this pixel, make the pixmap transparent too
            if mask_pixel.alpha() == 0 {
                let idx = (y * width + x) as usize;
                pixmap.pixels_mut()[idx] = tiny_skia::ColorU8::from_rgba(0, 0, 0, 0).premultiply();
            }
        }
    }
}

fn get_bundled_icons_path() -> PathBuf {
    // Icons are bundled with the binary in the icons/ directory
    // This could be relative to the current directory or the binary location
    let current_dir_path = PathBuf::from("icons/Asset-Package.7z");
    if current_dir_path.exists() {
        return current_dir_path;
    }

    // Try relative to the executable
    if let Ok(exe_path) = std::env::current_exe() {
        if let Some(exe_dir) = exe_path.parent() {
            let exe_relative = exe_dir.join("icons/Asset-Package.7z");
            if exe_relative.exists() {
                return exe_relative;
            }
            // Try one level up (for cargo build structure)
            if let Some(parent) = exe_dir.parent() {
                let parent_relative = parent.join("icons/Asset-Package.7z");
                if parent_relative.exists() {
                    return parent_relative;
                }
            }
        }
    }

    // Default to current directory path
    current_dir_path
}

fn get_icon_search_pattern(name: &str) -> Option<&'static str> {
    // Search patterns for finding icons in the ZIP by filename
    // These work across different AWS icon package versions
    match name {
        // Compute
        "ec2" => Some("Amazon-EC2_64"),
        "lambda" => Some("AWS-Lambda_64"),
        "ecs" => Some("Amazon-Elastic-Container-Service_64"),
        "eks" => Some("Amazon-Elastic-Kubernetes-Service_64"),
        "autoscaling" => Some("AWS-Auto-Scaling_64"),

        // Database
        "rds" => Some("Amazon-RDS_64"),
        "dynamodb" => Some("Amazon-DynamoDB_64"),
        "elasticache" => Some("Amazon-ElastiCache_64"),
        "redshift" => Some("Amazon-Redshift_64"),

        // Network
        "elb" => Some("Elastic-Load-Balancing_64"),
        "vpc" => Some("Amazon-Virtual-Private-Cloud_64"),
        "subnet" => Some("Amazon-Virtual-Private-Cloud_64"), // Use VPC icon
        "route53" => Some("Amazon-Route-53_64"),
        "cloudfront" => Some("Amazon-CloudFront_64"),
        "apigateway" => Some("Amazon-API-Gateway_64"),

        // Storage
        "s3" => Some("Amazon-Simple-Storage-Service_64"),
        "ebs" => Some("Amazon-Elastic-Block-Store_64"),
        // Note: EFS icon not available in bundled AWS Architecture Icons archive
        // "efs" => Some("Amazon-Elastic-File-System_64"),

        // Security
        "iam" => Some("AWS-Identity-and-Access-Management_64"),
        "kms" => Some("AWS-Key-Management-Service_64"),

        // Integration
        "sns" => Some("Amazon-Simple-Notification-Service_64"),
        "sqs" => Some("Amazon-Simple-Queue-Service_64"),

        // Analytics
        "kinesis" => Some("Amazon-Kinesis_64"),

        _ => None,
    }
}

fn extract_icons_from_7z(archive_path: &Path, cache_dir: &Path) -> Result<usize> {
    eprintln!("Extracting AWS Architecture Icons from bundled archive...");

    let icon_names = vec![
        "ec2", "lambda", "ecs", "eks", "autoscaling",
        "rds", "dynamodb", "elasticache", "redshift",
        "elb", "vpc", "subnet", "route53", "cloudfront", "apigateway",
        "s3", "ebs",
        // Note: EFS icon not available in bundled AWS Architecture Icons archive
        "iam", "kms",
        "sns", "sqs",
        "kinesis",
    ];

    let mut extracted_count = 0;

    // Create a temporary directory for extraction
    let temp_dir = tempfile::tempdir()
        .context("Failed to create temporary directory")?;

    // Extract the 7z archive to temp directory
    sevenz_rust::decompress_file(archive_path, temp_dir.path())
        .map_err(|e| anyhow::anyhow!("Failed to extract 7z archive: {}", e))?;

    // Now search the extracted files for our icons and cache SVGs
    for name in &icon_names {
        // Skip if already cached as SVG
        let svg_cache_path = cache_dir.join(format!("{}.svg", name));
        if svg_cache_path.exists() {
            extracted_count += 1;
            continue;
        }

        // Get the search pattern for this icon
        if let Some(pattern) = get_icon_search_pattern(name) {
            // Search recursively from the temp directory root
            if let Some(svg_path) = find_icon_in_dir(temp_dir.path(), pattern) {
                // Copy SVG to cache (will be converted to PNG lazily when needed)
                fs::copy(&svg_path, &svg_cache_path)?;
                extracted_count += 1;
            }
        }
    }

    Ok(extracted_count)
}

fn find_icon_in_dir(dir: &Path, pattern: &str) -> Option<PathBuf> {
    // Recursively search for an icon matching the pattern
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_file() {
                if let Some(filename) = path.file_name().and_then(|n| n.to_str()) {
                    // Check if this file matches our search pattern and is an SVG
                    if filename.contains(pattern) && filename.ends_with(".svg") {
                        // Prefer 64x64 size icons (though SVGs are scalable)
                        if filename.contains("_64") || path.to_str().map_or(false, |p| p.contains("/64/")) {
                            return Some(path);
                        }
                    }
                }
            } else if path.is_dir() {
                // Recurse into subdirectories
                if let Some(found) = find_icon_in_dir(&path, pattern) {
                    return Some(found);
                }
            }
        }
    }
    None
}

fn download_icons_as_needed(cache_dir: &Path) -> Result<()> {
    let icon_names = vec![
        "ec2", "lambda", "ecs", "eks", "autoscaling",
        "rds", "dynamodb", "elasticache", "redshift",
        "elb", "vpc", "subnet", "route53", "cloudfront", "apigateway",
        "s3", "ebs",
        // Note: EFS icon not available in bundled AWS Architecture Icons archive
        "iam", "kms",
        "sns", "sqs",
        "kinesis",
    ];

    // Check if we need to extract any icons (SVG format)
    let needs_extraction = icon_names.iter().any(|name| {
        !cache_dir.join(format!("{}.svg", name)).exists()
    });

    if !needs_extraction {
        return Ok(()); // All icons already cached
    }

    eprintln!("Setting up AWS service icons (first run)...");

    // Get path to bundled icons archive
    let archive_path = get_bundled_icons_path();

    if !archive_path.exists() {
        eprintln!("Note: Bundled icons archive not found. Using fallback styled boxes.");
        eprintln!("Expected location: {}", archive_path.display());
        return Ok(());
    }

    // Extract the icons we need from the bundled 7z archive
    match extract_icons_from_7z(&archive_path, cache_dir) {
        Ok(count) => {
            if count > 0 {
                eprintln!("✓ Extracted {} AWS service icons", count);
            } else {
                eprintln!("Note: Could not extract icons. Using fallback styled boxes.");
            }
        }
        Err(e) => {
            eprintln!("Note: Icon extraction failed ({}). Using fallback styled boxes.", e);
        }
    }

    Ok(())
}

fn parse_dot_graph(dot_content: &str) -> Result<TerraformGraph> {
    let mut graph = TerraformGraph::new();

    // Regex to match node definitions
    let node_re = Regex::new(r#"\[root\] ([^\s]+) \(([^)]+)\)"#)?;
    // Updated edge regex to handle quoted format: "[root] aws_instance.web (expand)" -> "[root] aws_vpc.main (expand)"
    let edge_re = Regex::new(r#""\[root\] ([^\s]+) \([^)]+\)" -> "\[root\] ([^\s]+) \([^)]+\)""#)?;
    let label_re = Regex::new(r#"label = "([^"]+)""#)?;

    let mut node_map: HashMap<String, (String, String)> = HashMap::new();

    for line in dot_content.lines() {
        let line = line.trim();

        // Parse node definitions
        if line.contains("[label =") {
            if let Some(caps) = node_re.captures(line) {
                let full_name = caps.get(1).map_or("", |m| m.as_str()).to_string();

                // Extract resource type from the node name (e.g., "aws_instance" from "aws_instance.web")
                let resource_type = if let Some(dot_pos) = full_name.find('.') {
                    full_name[..dot_pos].to_string()
                } else {
                    full_name.clone()
                };

                let label = label_re
                    .captures(line)
                    .and_then(|c| c.get(1))
                    .map_or(full_name.clone(), |m| m.as_str().to_string());

                node_map.insert(full_name.clone(), (resource_type, label));
            }
        }

        // Parse edges
        if line.contains("->") {
            if let Some(caps) = edge_re.captures(line) {
                let from = caps.get(1).map_or("", |m| m.as_str()).to_string();
                let to = caps.get(2).map_or("", |m| m.as_str()).to_string();
                graph.add_edge(from, to);
            }
        }
    }

    // Add all nodes to the graph
    for (name, (resource_type, label)) in node_map {
        graph.add_resource(name, resource_type, label);
    }

    Ok(graph)
}

fn get_service_info(resource_type: &str) -> (&str, &str, &str, &str) {
    // Returns (icon_name, service_name, color, fallback_emoji)
    match resource_type {
        // Compute
        t if t.contains("aws_instance") => ("ec2", "EC2", "#FF9900", "💻"),
        t if t.contains("aws_lambda") => ("lambda", "Lambda", "#FF9900", "λ"),
        t if t.contains("aws_ecs") => ("ecs", "ECS", "#FF9900", "🐳"),
        t if t.contains("aws_eks") => ("eks", "EKS", "#FF9900", "☸"),
        t if t.contains("aws_autoscaling") => ("autoscaling", "AutoScaling", "#FF9900", "📈"),

        // Database
        t if t.contains("aws_db_instance") => ("rds", "RDS", "#3B48CC", "🗄"),
        t if t.contains("aws_db_subnet_group") => ("rds", "RDS", "#3B48CC", "🗄"),
        t if t.contains("aws_dynamodb") => ("dynamodb", "DynamoDB", "#3B48CC", "⚡"),
        t if t.contains("aws_elasticache") => ("elasticache", "ElastiCache", "#3B48CC", "💾"),
        t if t.contains("aws_redshift") => ("redshift", "Redshift", "#3B48CC", "🔷"),

        // Network
        t if t.contains("aws_elb") || t.contains("aws_lb") => ("elb", "ELB", "#8C4FFF", "⚖"),
        t if t.contains("aws_vpc") => ("vpc", "VPC", "#8C4FFF", "🌐"),
        t if t.contains("aws_subnet") => ("subnet", "Subnet", "#8C4FFF", "📡"),
        t if t.contains("aws_security_group") => ("vpc", "SecurityGroup", "#DD344C", "🛡"),
        t if t.contains("aws_route53") => ("route53", "Route53", "#8C4FFF", "🌍"),
        t if t.contains("aws_cloudfront") => ("cloudfront", "CloudFront", "#8C4FFF", "☁"),
        t if t.contains("aws_api_gateway") => ("apigateway", "APIGateway", "#8C4FFF", "🚪"),

        // Storage
        t if t.contains("aws_s3") => ("s3", "S3", "#7AA116", "🪣"),
        t if t.contains("aws_ebs") => ("ebs", "EBS", "#7AA116", "💽"),
        t if t.contains("aws_efs") => ("efs", "EFS", "#7AA116", "📁"),

        // Security
        t if t.contains("aws_iam") => ("iam", "IAM", "#DD344C", "🔑"),
        t if t.contains("aws_kms") => ("kms", "KMS", "#DD344C", "🔐"),

        // Integration
        t if t.contains("aws_sns") => ("sns", "SNS", "#FF4F8B", "📢"),
        t if t.contains("aws_sqs") => ("sqs", "SQS", "#FF4F8B", "📬"),

        // Analytics
        t if t.contains("aws_kinesis") => ("kinesis", "Kinesis", "#8C4FFF", "📊"),

        // Default
        _ => ("", "Service", "#232F3E", "🔧"),
    }
}

fn generate_dot_graph(graph: &TerraformGraph, name: &str, direction: &str, cache_dir: &Path, temp_dir: &Path, icon_size: u32, color: &str) -> Result<String> {
    let mut dot = String::new();

    // Graph header with modern styling
    dot.push_str(&format!("digraph \"{}\" {{\n", name));
    dot.push_str("    graph [fontname=\"Arial\", fontsize=14, bgcolor=\"transparent\", pad=\"0.5\"];\n");
    dot.push_str("    node [fontname=\"Arial\", fontsize=11];\n");
    dot.push_str(&format!("    edge [fontname=\"Arial\", fontsize=10, color=\"{}\", penwidth=2.0, arrowsize=0.7];\n", color));
    dot.push_str(&format!("    rankdir={};\n", direction));
    dot.push_str("    splines=ortho;\n");
    dot.push_str("    nodesep=1.0;\n");
    dot.push_str("    ranksep=1.5;\n\n");

    // Filter AWS resources only
    let aws_resources: Vec<_> = graph.resources.iter()
        .filter(|r| r.resource_type.contains("aws_"))
        .collect();

    let mut node_map: HashMap<String, String> = HashMap::new();

    // Generate nodes
    for (idx, resource) in aws_resources.iter().enumerate() {
        let node_id = format!("node_{}", idx);
        let (icon_name, service_name, color, _fallback_emoji) = get_service_info(&resource.resource_type);

        // Check if we have a cached SVG icon
        let svg_path = cache_dir.join(format!("{}.svg", icon_name));

        // Use icon if available, otherwise use colored box
        if svg_path.exists() && !icon_name.is_empty() {
            // Convert SVG to PNG for all output formats
            let png_path = temp_dir.join(format!("{}.png", icon_name));

            match convert_svg_to_png(&svg_path, &png_path, icon_size) {
                Ok(_) => {
                    let icon_path_str = png_path.to_string_lossy();
                    // GraphViz: HTML-like label with image in table cell and colored text below
                    // Set FIXEDSIZE on TD to constrain image proportionally for PDF output
                    // Text color matches the edge color
                    let html_label = format!(
                        "<<TABLE BORDER=\"0\" CELLBORDER=\"0\" CELLSPACING=\"0\"><TR><TD FIXEDSIZE=\"TRUE\" WIDTH=\"{}\" HEIGHT=\"{}\"><IMG SRC=\"{}\"/></TD></TR><TR><TD><FONT COLOR=\"{}\">{}</FONT></TD></TR></TABLE>>",
                        icon_size, icon_size, icon_path_str, color, resource.label
                    );
                    dot.push_str(&format!(
                        "    {} [label={}, shape=plaintext, fontsize=10];\n",
                        node_id, html_label
                    ));
                }
                Err(_) => {
                    // Fallback to styled box if conversion fails
                    let label = format!("{}\\n{}", service_name, resource.label);
                    dot.push_str(&format!(
                        "    {} [label=\"{}\", fillcolor=\"{}\", fontcolor=\"white\", style=\"filled,rounded\", shape=box, width=1.5, height=1.0];\n",
                        node_id, label, color
                    ));
                }
            }
        } else {
            // Fallback to styled box with service name
            let label = format!("{}\\n{}", service_name, resource.label);
            dot.push_str(&format!(
                "    {} [label=\"{}\", fillcolor=\"{}\", fontcolor=\"white\", style=\"filled,rounded\", shape=box, width=1.5, height=1.0];\n",
                node_id, label, color
            ));
        }

        node_map.insert(resource.name.clone(), node_id);
    }

    dot.push_str("\n");

    // Generate edges
    for (from, to) in &graph.edges {
        if let (Some(from_node), Some(to_node)) = (node_map.get(from), node_map.get(to)) {
            dot.push_str(&format!("    {} -> {};\n", from_node, to_node));
        }
    }

    dot.push_str("}\n");
    Ok(dot)
}

fn execute_dot_command(dot_content: &str, output_format: &str, output_file: &str) -> Result<()> {
    // Check if dot command exists
    let dot_check = Command::new("dot")
        .arg("-V")
        .output();

    if dot_check.is_err() {
        anyhow::bail!(
            "GraphViz 'dot' command not found. Please install GraphViz:\n\
             - macOS: brew install graphviz\n\
             - Ubuntu/Debian: sudo apt-get install graphviz\n\
             - Fedora: sudo dnf install graphviz\n\
             - Windows: Download from https://graphviz.org/download/"
        );
    }

    // Create temporary file for DOT content
    let mut temp_file = NamedTempFile::new()?;
    temp_file.write_all(dot_content.as_bytes())?;
    let temp_path = temp_file.path();

    // Execute dot command
    let output = Command::new("dot")
        .arg(format!("-T{}", output_format))
        .arg(temp_path)
        .arg("-o")
        .arg(output_file)
        .output()
        .context("Failed to execute dot command")?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!("GraphViz dot command failed: {}", stderr);
    }

    Ok(())
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    // Read from stdin
    let mut input = String::new();
    io::stdin()
        .read_to_string(&mut input)
        .context("Failed to read from stdin")?;

    if input.trim().is_empty() {
        anyhow::bail!("No input provided. Please pipe terraform graph output to agedashi.");
    }

    // Parse the Terraform graph
    let graph = parse_dot_graph(&input).context("Failed to parse Terraform graph")?;

    if graph.resources.is_empty() {
        eprintln!("Warning: No resources found in the Terraform graph.");
    }

    eprintln!("Found {} resources and {} edges", graph.resources.len(), graph.edges.len());

    // Filter for AWS resources
    let aws_count = graph.resources.iter().filter(|r| r.resource_type.contains("aws_")).count();

    if aws_count == 0 {
        eprintln!("Warning: No AWS resources found to visualize.");
        return Ok(());
    }

    eprintln!("Visualizing {} AWS resources...", aws_count);

    // Get cache directory and setup icons
    let cache_dir = get_cache_dir()?;

    // First, extract any embedded icons (from build-time)
    extract_embedded_icons(&cache_dir)?;

    // Then, download any missing icons from the internet (cached)
    download_icons_as_needed(&cache_dir)?;

    // Count how many icons we have available (SVG format)
    let icon_count = ["ec2", "lambda", "ecs", "eks", "autoscaling",
                      "rds", "dynamodb", "elasticache", "redshift",
                      "elb", "vpc", "subnet", "route53", "cloudfront", "apigateway",
                      "s3", "ebs", "iam", "kms", "sns", "sqs", "kinesis"]
        .iter()
        .filter(|name| cache_dir.join(format!("{}.svg", name)).exists())
        .count();

    if icon_count > 0 {
        eprintln!("Using {} AWS service icons", icon_count);
    } else {
        eprintln!("Using fallback styled boxes (icons unavailable)");
    }

    // Create temp directory for PNG conversions
    let temp_dir = tempfile::tempdir()
        .context("Failed to create temporary directory for icon conversion")?;

    // Generate DOT graph with lazy icon conversion
    // Icons are converted from SVG to PNG at 128x128
    // For SVG output, the generated SVG is post-processed to embed PNGs as base64
    let dot_content = generate_dot_graph(&graph, &cli.name, &cli.direction, &cache_dir, temp_dir.path(), 128, &cli.color)?;

    // Output file path
    let output_file = format!("{}.{}", cli.name, cli.output);

    // For debugging: save DOT file in debug mode
    if std::env::var("AGEDASHI_DEBUG").is_ok() {
        let dot_file = format!("{}.dot", cli.name);
        fs::write(&dot_file, &dot_content)
            .context(format!("Failed to save DOT file: {}", dot_file))?;
        eprintln!("Debug: DOT file saved to {}", dot_file);
    }

    // Execute dot command
    execute_dot_command(&dot_content, &cli.output, &output_file)?;

    // For SVG output, post-process to embed images as base64 data URIs
    if cli.output == "svg" {
        embed_images_in_svg(&output_file)?;
    }

    println!("Diagram generated successfully: {}", output_file);

    Ok(())
}

// Post-process SVG to embed PNG images as base64 data URIs
fn embed_images_in_svg(svg_file: &str) -> Result<()> {
    // Read the SVG file
    let svg_content = fs::read_to_string(svg_file)
        .context(format!("Failed to read SVG file: {}", svg_file))?;

    // Replace file paths with base64 data URIs
    let re = Regex::new(r#"xlink:href="([^"]+\.png)""#)?;
    let mut modified_svg = svg_content.clone();

    for cap in re.captures_iter(&svg_content) {
        let file_path = &cap[1];
        // Read the PNG file and base64 encode it
        if let Ok(png_data) = fs::read(file_path) {
            let base64_data = BASE64.encode(&png_data);
            let data_uri = format!("data:image/png;base64,{}", base64_data);
            modified_svg = modified_svg.replace(
                &format!("xlink:href=\"{}\"", file_path),
                &format!("xlink:href=\"{}\"", data_uri)
            );
        }
    }

    // Write the modified SVG back
    fs::write(svg_file, modified_svg)
        .context(format!("Failed to write modified SVG: {}", svg_file))?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_all_aws_resource_icons() {
        // This test validates that we can resolve icons for all AWS resource types
        // that are defined in our icon mapping. It ensures:
        // 1. Icons can be extracted from the bundled archive
        // 2. SVG to PNG conversion works correctly
        // 3. All resource types in the test fixture are handled

        // Create temporary directories for cache and output
        let temp_dir = tempfile::tempdir().expect("Failed to create temp dir");
        let cache_dir = temp_dir.path().join("cache");
        fs::create_dir_all(&cache_dir).expect("Failed to create cache dir");

        // Ensure icons are available (extract if needed)
        let bundled_icons = get_bundled_icons_path();
        if bundled_icons.exists() {
            let extracted = extract_icons_from_7z(&bundled_icons, &cache_dir)
                .expect("Failed to extract icons");
            println!("Extracted {} icons from archive", extracted);
        } else {
            panic!("Bundled icons not found at {:?}", bundled_icons);
        }

        // Parse the test fixture with all AWS resource types
        let test_dot_path = "test/all-aws-resources.dot";
        let dot_content = fs::read_to_string(test_dot_path)
            .expect(&format!("Failed to read test fixture: {}", test_dot_path));

        let graph = parse_dot_graph(&dot_content)
            .expect("Failed to parse test fixture");

        // Expected resource types that should have icons
        let expected_icon_types = vec![
            "autoscaling", "cloudfront", "dynamodb", "ebs", "ec2", "ecs",
            "eks", "elasticache", "elb", "iam", "apigateway",
            "kinesis", "kms", "lambda", "rds", "redshift", "route53",
            "s3", "sns", "sqs", "subnet", "vpc"
        ];

        // Track which resource types we found and their status
        let mut found_types = std::collections::HashSet::new();
        let mut successful_icons = Vec::new();
        let mut failed_icons = Vec::new();
        let mut missing_icons = Vec::new();

        // Filter AWS resources only (same as generate_dot_graph)
        let aws_resources: Vec<_> = graph.resources.iter()
            .filter(|r| r.resource_type.contains("aws_"))
            .collect();

        // Try to resolve an icon for each resource in the graph
        for resource in &aws_resources {
            let (icon_name, _service_name, _color, _fallback_emoji) = get_service_info(&resource.resource_type);
            found_types.insert(icon_name.to_string());

            // Check if we have a cached SVG icon
            let svg_path = cache_dir.join(format!("{}.svg", icon_name));

            if svg_path.exists() && !icon_name.is_empty() {
                // Try to convert SVG to PNG (same as generate_dot_graph)
                let png_path = temp_dir.path().join(format!("{}.png", icon_name));

                match convert_svg_to_png(&svg_path, &png_path, 128) {
                    Ok(_) => {
                        successful_icons.push(icon_name.to_string());
                    }
                    Err(e) => {
                        failed_icons.push(format!("{} (conversion failed: {})", icon_name, e));
                    }
                }
            } else if !icon_name.is_empty() {
                missing_icons.push(icon_name.to_string());
            }
        }

        // Report results
        println!("\n═══════════════════════════════════════════════════");
        println!("Icon Resolution Test Results");
        println!("═══════════════════════════════════════════════════");
        println!("  Resources tested: {}", aws_resources.len());
        println!("  Unique icon types: {}", found_types.len());
        println!("  Expected types: {}", expected_icon_types.len());
        println!("  ✓ Successful: {}", successful_icons.len());
        println!("  ✗ Missing from archive: {}", missing_icons.len());
        println!("  ✗ Conversion failures: {}", failed_icons.len());

        if !missing_icons.is_empty() {
            println!("\n  Icons not found in archive:");
            for icon in &missing_icons {
                println!("    - {}", icon);
            }
            println!("\n  Note: These icons may not exist in the bundled AWS Architecture Icons archive,");
            println!("        or the search pattern may need adjustment.");
        }

        if !failed_icons.is_empty() {
            println!("\n  Conversion failures (CRITICAL):");
            for icon in &failed_icons {
                println!("    - {}", icon);
            }
        }

        // Check that all expected types were covered in test fixture
        let mut missing_from_fixture = Vec::new();
        for expected in &expected_icon_types {
            if !found_types.contains(*expected) {
                missing_from_fixture.push(*expected);
            }
        }

        if !missing_from_fixture.is_empty() {
            println!("\n  Warning: Expected icon types not in test fixture:");
            for missing in &missing_from_fixture {
                println!("    - {}", missing);
            }
        }

        println!("═══════════════════════════════════════════════════\n");

        // Test passes if:
        // 1. No conversion failures (critical - code is broken)
        // 2. At least 90% of icons are available (allows for archive changes)
        let success_rate = successful_icons.len() as f32 / aws_resources.len() as f32;

        assert!(
            failed_icons.is_empty(),
            "Icon conversion failures detected. This indicates a bug in the code."
        );

        assert!(
            success_rate >= 0.9,
            "Only {:.1}% of icons available (expected >= 90%). Missing: {:?}",
            success_rate * 100.0,
            missing_icons
        );
    }
}
