use anyhow::{Context, Result};
use clap::Parser;
use regex::Regex;
use std::collections::HashMap;
use std::fs;
use std::io::{self, Read, Write as IoWrite};
use std::path::{Path, PathBuf};
use std::process::Command;
use tempfile::NamedTempFile;
use zip::ZipArchive;

// Include embedded icons (generated by build.rs)
include!(concat!(env!("OUT_DIR"), "/icons.rs"));

#[derive(Parser, Debug)]
#[command(name = "agedashi")]
#[command(about = "Generate infrastructure diagrams from Terraform/OpenTofu graph output - making tofu pretty!", long_about = None)]
struct Cli {
    /// Output format (svg, png, pdf, jpg)
    #[arg(short, long, default_value = "png")]
    output: String,

    /// Output file name (without extension)
    #[arg(short, long, default_value = "infrastructure")]
    name: String,

    /// Show graph direction (TB=top-to-bottom, LR=left-to-right)
    #[arg(short, long, default_value = "TB")]
    direction: String,
}

#[derive(Debug, Clone)]
struct TerraformResource {
    name: String,
    resource_type: String,
    label: String,
}

#[derive(Debug)]
struct TerraformGraph {
    resources: Vec<TerraformResource>,
    edges: Vec<(String, String)>,
}

impl TerraformGraph {
    fn new() -> Self {
        Self {
            resources: Vec::new(),
            edges: Vec::new(),
        }
    }

    fn add_resource(&mut self, name: String, resource_type: String, label: String) {
        self.resources.push(TerraformResource {
            name,
            resource_type,
            label,
        });
    }

    fn add_edge(&mut self, from: String, to: String) {
        self.edges.push((from, to));
    }
}

fn get_cache_dir() -> Result<PathBuf> {
    let cache_dir = if let Ok(home) = std::env::var("HOME") {
        PathBuf::from(home).join(".cache").join("agedashi").join("icons")
    } else if let Ok(userprofile) = std::env::var("USERPROFILE") {
        PathBuf::from(userprofile).join(".cache").join("agedashi").join("icons")
    } else {
        PathBuf::from("/tmp").join("agedashi").join("icons")
    };

    fs::create_dir_all(&cache_dir)
        .context("Failed to create cache directory")?;

    Ok(cache_dir)
}

fn extract_embedded_icons(cache_dir: &Path) -> Result<()> {
    let embedded_icons = get_embedded_icons();

    for (name, data) in embedded_icons {
        let icon_path = cache_dir.join(format!("{}.png", name));

        // Only write if file doesn't exist
        if !icon_path.exists() {
            fs::write(&icon_path, data)
                .context(format!("Failed to extract icon: {}", name))?;
        }
    }

    Ok(())
}

fn download_aws_icons_zip(cache_dir: &Path) -> Result<PathBuf> {
    // Official AWS Architecture Icons download URL
    // Using the July 2025 release from the official AWS approved architecture icons
    let zip_url = "https://d1.awsstatic.com/onedam/marketing-channels/website/aws/en_US/architecture/approved/architecture-icons/Asset-Package_07312025.49d3aab7f9e6131e51ade8f7c6c8b961ee7d3bb1.zip";
    let zip_path = cache_dir.join("aws-icons.zip");

    // Skip if already downloaded
    if zip_path.exists() {
        return Ok(zip_path);
    }

    eprintln!("Downloading official AWS Architecture Icons package...");
    eprintln!("This is a one-time download (~50MB)");

    // Download the ZIP file
    match ureq::get(zip_url).timeout(std::time::Duration::from_secs(60)).call() {
        Ok(response) => {
            let mut bytes = Vec::new();
            response.into_reader().read_to_end(&mut bytes)?;
            fs::write(&zip_path, bytes)
                .context("Failed to save AWS icons ZIP file")?;
            eprintln!("✓ Downloaded AWS Architecture Icons package");
        }
        Err(e) => {
            return Err(anyhow::anyhow!("Failed to download AWS icons: {}", e));
        }
    }

    Ok(zip_path)
}

fn get_icon_search_pattern(name: &str) -> Option<&'static str> {
    // Search patterns for finding icons in the ZIP by filename
    // These work across different AWS icon package versions
    match name {
        // Compute
        "ec2" => Some("Amazon-EC2_64"),
        "lambda" => Some("AWS-Lambda_64"),
        "ecs" => Some("Amazon-Elastic-Container-Service_64"),
        "eks" => Some("Amazon-Elastic-Kubernetes-Service_64"),
        "autoscaling" => Some("AWS-Auto-Scaling_64"),

        // Database
        "rds" => Some("Amazon-RDS_64"),
        "dynamodb" => Some("Amazon-DynamoDB_64"),
        "elasticache" => Some("Amazon-ElastiCache_64"),
        "redshift" => Some("Amazon-Redshift_64"),

        // Network
        "elb" => Some("Elastic-Load-Balancing_64"),
        "vpc" => Some("Amazon-Virtual-Private-Cloud_64"),
        "subnet" => Some("Amazon-Virtual-Private-Cloud_64"), // Use VPC icon
        "route53" => Some("Amazon-Route-53_64"),
        "cloudfront" => Some("Amazon-CloudFront_64"),
        "apigateway" => Some("Amazon-API-Gateway_64"),

        // Storage
        "s3" => Some("Amazon-Simple-Storage-Service_64"),
        "ebs" => Some("Amazon-Elastic-Block-Store_64"),
        "efs" => Some("Amazon-Elastic-File-System_64"),

        // Security
        "iam" => Some("AWS-Identity-and-Access-Management_64"),
        "kms" => Some("AWS-Key-Management-Service_64"),

        // Integration
        "sns" => Some("Amazon-Simple-Notification-Service_64"),
        "sqs" => Some("Amazon-Simple-Queue-Service_64"),

        // Analytics
        "kinesis" => Some("Amazon-Kinesis_64"),

        _ => None,
    }
}

fn extract_icons_from_zip(zip_path: &Path, cache_dir: &Path) -> Result<usize> {
    let file = fs::File::open(zip_path)
        .context("Failed to open AWS icons ZIP file")?;
    let mut archive = ZipArchive::new(file)
        .context("Failed to read ZIP archive")?;

    let icon_names = vec![
        "ec2", "lambda", "ecs", "eks", "autoscaling",
        "rds", "dynamodb", "elasticache", "redshift",
        "elb", "vpc", "subnet", "route53", "cloudfront", "apigateway",
        "s3", "ebs", "efs",
        "iam", "kms",
        "sns", "sqs",
        "kinesis",
    ];

    let mut extracted_count = 0;

    for name in &icon_names {
        // Skip if already extracted
        let output_path = cache_dir.join(format!("{}.png", name));
        if output_path.exists() {
            extracted_count += 1;
            continue;
        }

        // Get the search pattern for this icon
        if let Some(pattern) = get_icon_search_pattern(name) {
            // Try to find and extract the file from the ZIP
            // Search by filename pattern to handle different ZIP structures
            for i in 0..archive.len() {
                let mut file = archive.by_index(i)?;
                let file_path = file.name().to_string();

                // Check if this file matches our search pattern and is a PNG
                if file_path.contains(pattern) && file_path.ends_with(".png") {
                    // Prefer 64x64 size icons
                    if file_path.contains("/64/") || file_path.contains("_64") {
                        let mut buffer = Vec::new();
                        file.read_to_end(&mut buffer)?;
                        fs::write(&output_path, buffer)?;
                        extracted_count += 1;
                        break;
                    }
                }
            }
        }
    }

    Ok(extracted_count)
}

fn download_icons_as_needed(cache_dir: &Path) -> Result<()> {
    let icon_names = vec![
        "ec2", "lambda", "ecs", "eks", "autoscaling",
        "rds", "dynamodb", "elasticache", "redshift",
        "elb", "vpc", "subnet", "route53", "cloudfront", "apigateway",
        "s3", "ebs", "efs",
        "iam", "kms",
        "sns", "sqs",
        "kinesis",
    ];

    // Check if we need to download any icons
    let needs_download = icon_names.iter().any(|name| {
        !cache_dir.join(format!("{}.png", name)).exists()
    });

    if !needs_download {
        return Ok(()); // All icons already cached
    }

    eprintln!("Setting up AWS service icons (first run)...");

    // Download the official AWS Architecture Icons ZIP
    match download_aws_icons_zip(cache_dir) {
        Ok(zip_path) => {
            // Extract the icons we need
            match extract_icons_from_zip(&zip_path, cache_dir) {
                Ok(count) => {
                    if count > 0 {
                        eprintln!("✓ Extracted {} AWS service icons", count);
                    } else {
                        eprintln!("Note: Could not extract icons. Using fallback styled boxes.");
                    }
                }
                Err(e) => {
                    eprintln!("Note: Icon extraction failed ({}). Using fallback styled boxes.", e);
                }
            }
        }
        Err(e) => {
            eprintln!("Note: Icon download failed ({}). Using fallback styled boxes.", e);
        }
    }

    Ok(())
}

fn parse_dot_graph(dot_content: &str) -> Result<TerraformGraph> {
    let mut graph = TerraformGraph::new();

    // Regex to match node definitions
    let node_re = Regex::new(r#"\[root\] ([^\s]+) \(([^)]+)\)"#)?;
    // Updated edge regex to handle quoted format: "[root] aws_instance.web (expand)" -> "[root] aws_vpc.main (expand)"
    let edge_re = Regex::new(r#""\[root\] ([^\s]+) \([^)]+\)" -> "\[root\] ([^\s]+) \([^)]+\)""#)?;
    let label_re = Regex::new(r#"label = "([^"]+)""#)?;

    let mut node_map: HashMap<String, (String, String)> = HashMap::new();

    for line in dot_content.lines() {
        let line = line.trim();

        // Parse node definitions
        if line.contains("[label =") {
            if let Some(caps) = node_re.captures(line) {
                let full_name = caps.get(1).map_or("", |m| m.as_str()).to_string();

                // Extract resource type from the node name (e.g., "aws_instance" from "aws_instance.web")
                let resource_type = if let Some(dot_pos) = full_name.find('.') {
                    full_name[..dot_pos].to_string()
                } else {
                    full_name.clone()
                };

                let label = label_re
                    .captures(line)
                    .and_then(|c| c.get(1))
                    .map_or(full_name.clone(), |m| m.as_str().to_string());

                node_map.insert(full_name.clone(), (resource_type, label));
            }
        }

        // Parse edges
        if line.contains("->") {
            if let Some(caps) = edge_re.captures(line) {
                let from = caps.get(1).map_or("", |m| m.as_str()).to_string();
                let to = caps.get(2).map_or("", |m| m.as_str()).to_string();
                graph.add_edge(from, to);
            }
        }
    }

    // Add all nodes to the graph
    for (name, (resource_type, label)) in node_map {
        graph.add_resource(name, resource_type, label);
    }

    Ok(graph)
}

fn get_service_info(resource_type: &str) -> (&str, &str, &str, &str) {
    // Returns (icon_name, service_name, color, fallback_emoji)
    match resource_type {
        // Compute
        t if t.contains("aws_instance") => ("ec2", "EC2", "#FF9900", "💻"),
        t if t.contains("aws_lambda") => ("lambda", "Lambda", "#FF9900", "λ"),
        t if t.contains("aws_ecs") => ("ecs", "ECS", "#FF9900", "🐳"),
        t if t.contains("aws_eks") => ("eks", "EKS", "#FF9900", "☸"),
        t if t.contains("aws_autoscaling") => ("autoscaling", "AutoScaling", "#FF9900", "📈"),

        // Database
        t if t.contains("aws_db_instance") => ("rds", "RDS", "#3B48CC", "🗄"),
        t if t.contains("aws_db_subnet_group") => ("rds", "RDS", "#3B48CC", "🗄"),
        t if t.contains("aws_dynamodb") => ("dynamodb", "DynamoDB", "#3B48CC", "⚡"),
        t if t.contains("aws_elasticache") => ("elasticache", "ElastiCache", "#3B48CC", "💾"),
        t if t.contains("aws_redshift") => ("redshift", "Redshift", "#3B48CC", "🔷"),

        // Network
        t if t.contains("aws_elb") || t.contains("aws_lb") => ("elb", "ELB", "#8C4FFF", "⚖"),
        t if t.contains("aws_vpc") => ("vpc", "VPC", "#8C4FFF", "🌐"),
        t if t.contains("aws_subnet") => ("subnet", "Subnet", "#8C4FFF", "📡"),
        t if t.contains("aws_security_group") => ("vpc", "SecurityGroup", "#DD344C", "🛡"),
        t if t.contains("aws_route53") => ("route53", "Route53", "#8C4FFF", "🌍"),
        t if t.contains("aws_cloudfront") => ("cloudfront", "CloudFront", "#8C4FFF", "☁"),
        t if t.contains("aws_api_gateway") => ("apigateway", "APIGateway", "#8C4FFF", "🚪"),

        // Storage
        t if t.contains("aws_s3") => ("s3", "S3", "#7AA116", "🪣"),
        t if t.contains("aws_ebs") => ("ebs", "EBS", "#7AA116", "💽"),
        t if t.contains("aws_efs") => ("efs", "EFS", "#7AA116", "📁"),

        // Security
        t if t.contains("aws_iam") => ("iam", "IAM", "#DD344C", "🔑"),
        t if t.contains("aws_kms") => ("kms", "KMS", "#DD344C", "🔐"),

        // Integration
        t if t.contains("aws_sns") => ("sns", "SNS", "#FF4F8B", "📢"),
        t if t.contains("aws_sqs") => ("sqs", "SQS", "#FF4F8B", "📬"),

        // Analytics
        t if t.contains("aws_kinesis") => ("kinesis", "Kinesis", "#8C4FFF", "📊"),

        // Default
        _ => ("", "Service", "#232F3E", "🔧"),
    }
}

fn generate_dot_graph(graph: &TerraformGraph, name: &str, direction: &str, cache_dir: &Path) -> String {
    let mut dot = String::new();

    // Graph header with modern styling
    dot.push_str(&format!("digraph \"{}\" {{\n", name));
    dot.push_str("    graph [fontname=\"Arial\", fontsize=14, bgcolor=\"#FFFFFF\", pad=\"0.5\"];\n");
    dot.push_str("    node [fontname=\"Arial\", fontsize=11];\n");
    dot.push_str("    edge [fontname=\"Arial\", fontsize=10, color=\"#2D3436\", penwidth=2.0, arrowsize=0.7];\n");
    dot.push_str(&format!("    rankdir={};\n", direction));
    dot.push_str("    splines=ortho;\n");
    dot.push_str("    nodesep=1.0;\n");
    dot.push_str("    ranksep=1.5;\n\n");

    // Filter AWS resources only
    let aws_resources: Vec<_> = graph.resources.iter()
        .filter(|r| r.resource_type.contains("aws_"))
        .collect();

    let mut node_map: HashMap<String, String> = HashMap::new();

    // Generate nodes
    for (idx, resource) in aws_resources.iter().enumerate() {
        let node_id = format!("node_{}", idx);
        let (icon_name, service_name, color, _fallback_emoji) = get_service_info(&resource.resource_type);

        let icon_path = cache_dir.join(format!("{}.png", icon_name));

        // Use icon if available, otherwise use colored box with emoji
        if icon_path.exists() && !icon_name.is_empty() {
            let icon_path_str = icon_path.to_string_lossy();
            // GraphViz: image with label below, proper sizing for clean icons
            // width=1.5, height=1.5 creates a 1.5"x1.5" square (standard for AWS icons)
            // imagepos=tc centers the image at top-center
            // penwidth=0 removes any border
            dot.push_str(&format!(
                "    {} [label=\"{}\", image=\"{}\", shape=none, labelloc=b, imagepos=tc, imagescale=true, fixedsize=true, width=1.5, height=1.5, fontsize=11, penwidth=0];\n",
                node_id, resource.label, icon_path_str
            ));
        } else {
            // Fallback to styled box with service name (no emoji - cleaner)
            let label = format!("{}\\n{}", service_name, resource.label);
            dot.push_str(&format!(
                "    {} [label=\"{}\", fillcolor=\"{}\", fontcolor=\"white\", style=\"filled,rounded\", shape=box, width=1.5, height=1.0];\n",
                node_id, label, color
            ));
        }

        node_map.insert(resource.name.clone(), node_id);
    }

    dot.push_str("\n");

    // Generate edges
    for (from, to) in &graph.edges {
        if let (Some(from_node), Some(to_node)) = (node_map.get(from), node_map.get(to)) {
            dot.push_str(&format!("    {} -> {};\n", from_node, to_node));
        }
    }

    dot.push_str("}\n");
    dot
}

fn execute_dot_command(dot_content: &str, output_format: &str, output_file: &str) -> Result<()> {
    // Check if dot command exists
    let dot_check = Command::new("dot")
        .arg("-V")
        .output();

    if dot_check.is_err() {
        anyhow::bail!(
            "GraphViz 'dot' command not found. Please install GraphViz:\n\
             - macOS: brew install graphviz\n\
             - Ubuntu/Debian: sudo apt-get install graphviz\n\
             - Fedora: sudo dnf install graphviz\n\
             - Windows: Download from https://graphviz.org/download/"
        );
    }

    // Create temporary file for DOT content
    let mut temp_file = NamedTempFile::new()?;
    temp_file.write_all(dot_content.as_bytes())?;
    let temp_path = temp_file.path();

    // Execute dot command
    let output = Command::new("dot")
        .arg(format!("-T{}", output_format))
        .arg(temp_path)
        .arg("-o")
        .arg(output_file)
        .output()
        .context("Failed to execute dot command")?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!("GraphViz dot command failed: {}", stderr);
    }

    Ok(())
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    // Read from stdin
    let mut input = String::new();
    io::stdin()
        .read_to_string(&mut input)
        .context("Failed to read from stdin")?;

    if input.trim().is_empty() {
        anyhow::bail!("No input provided. Please pipe terraform graph output to agedashi.");
    }

    // Parse the Terraform graph
    let graph = parse_dot_graph(&input).context("Failed to parse Terraform graph")?;

    if graph.resources.is_empty() {
        eprintln!("Warning: No resources found in the Terraform graph.");
    }

    eprintln!("Found {} resources and {} edges", graph.resources.len(), graph.edges.len());

    // Filter for AWS resources
    let aws_count = graph.resources.iter().filter(|r| r.resource_type.contains("aws_")).count();

    if aws_count == 0 {
        eprintln!("Warning: No AWS resources found to visualize.");
        return Ok(());
    }

    eprintln!("Visualizing {} AWS resources...", aws_count);

    // Get cache directory and setup icons
    let cache_dir = get_cache_dir()?;

    // First, extract any embedded icons (from build-time)
    extract_embedded_icons(&cache_dir)?;

    // Then, download any missing icons from the internet (cached)
    download_icons_as_needed(&cache_dir)?;

    // Count how many icons we have available
    let icon_count = ["ec2", "lambda", "ecs", "eks", "autoscaling",
                      "rds", "dynamodb", "elasticache", "redshift",
                      "elb", "vpc", "subnet", "route53", "cloudfront", "apigateway",
                      "s3", "ebs", "efs", "iam", "kms", "sns", "sqs", "kinesis"]
        .iter()
        .filter(|name| cache_dir.join(format!("{}.png", name)).exists())
        .count();

    if icon_count > 0 {
        eprintln!("Using {} AWS service icons", icon_count);
    } else {
        eprintln!("Using fallback styled boxes (icons unavailable)");
    }

    // Generate DOT graph
    let dot_content = generate_dot_graph(&graph, &cli.name, &cli.direction, &cache_dir);

    // Output file path
    let output_file = format!("{}.{}", cli.name, cli.output);

    // For debugging: save DOT file in debug mode
    if std::env::var("AGEDASHI_DEBUG").is_ok() {
        let dot_file = format!("{}.dot", cli.name);
        fs::write(&dot_file, &dot_content)
            .context(format!("Failed to save DOT file: {}", dot_file))?;
        eprintln!("Debug: DOT file saved to {}", dot_file);
    }

    // Execute dot command
    execute_dot_command(&dot_content, &cli.output, &output_file)?;

    println!("Diagram generated successfully: {}", output_file);

    Ok(())
}
